name: Unit test

on:
  push:
    branches:
      - master
      - release-*
    tags: ['*']
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.0', '1.6', '1', 'nightly']
        os: [ubuntu-latest, windows-latest, macos-13]
        julia-arch: [x64]
        include:
          - os: ubuntu-latest # only test one 32-bit job
            julia-version: '1'
            julia-arch: x86
          - os: macos-latest
            julia-version: '1'
            julia-arch: aarch64
          - os: macos-latest
            julia-version: 'nightly'
            julia-arch: aarch64

    steps:
      - uses: actions/checkout@v4
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: Cache artifacts
        uses: julia-actions/cache@v2
      - name: "Unit Test"
        uses: julia-actions/julia-runtest@v1

      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
          fail_ci_if_error: true
          file: lcov.info
